\set ON_ERROR_STOP on

DROP TABLE IF EXISTS "flight_events" CASCADE;
DROP TABLE IF EXISTS "flight_points" CASCADE;
DROP TABLE IF EXISTS "airspace_zones" CASCADE;
DROP TABLE IF EXISTS "flights" CASCADE;
DROP TABLE IF EXISTS "routes" CASCADE;
DROP TABLE IF EXISTS "aircraft" CASCADE;
DROP TABLE IF EXISTS "aircraft_models" CASCADE;
DROP TABLE IF EXISTS "airports" CASCADE;
DROP TABLE IF EXISTS "airlines" CASCADE;
DROP TABLE IF EXISTS "migrations" CASCADE;
DROP TABLE IF EXISTS "typeorm_metadata" CASCADE;
